### ISSUE TITLE
hub_connection.h: Cannot open source file "pplx\pplxtasks.h" and "cpprest\json.h"

### ISSUE THREAD

**Issue by MyPCIsBetter** [aspnet/SignalR-Client-Cpp#129]
I'm trying to run [[this code]](https://github.com/aspnet/SignalR-Client-Cpp/blob/dev/samples/HubConnectionSample/HubConnectionSample.cpp) in Visual Studio 2015, but it seems like some libraries are missing.
Packages in my project (packages.config):
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="cpprestsdk.v120.windesktop.msvcstl.dyn.rt-dyn" version="2.5.0" targetFramework="native" />
  <package id="Microsoft.AspNet.SignalR.Client.Cpp.v120.WinDesktop" version="1.0.0-alpha1" targetFramework="native" />
</packages>
```
[[Other errors]](http://imgur.com/4gj3jQP)
My project is simple windows console app, the code is exactly the same as in link I pasted here.

Is this some bug, or I'm doing something wrong?

**Comment by moozzyk** [comment]
The package that is currently on NuGet is only for VS2013. You can build one for VS2015 yourself from sources. In the VS2015 command prompt and run `msbuild build\build.msbuild /t:CreatePackage /p:Configuration=Release /p:Platform=x64`.
We are planning to put the VS2015 package on NuGet soon.

**Comment by MyPCIsBetter** [comment]
@moozzyk can you tell me what should I do after building this package? How to include it in project? It's probably obvious, but I'm not familar with Visual Studio yet.

**Comment by moozzyk** [comment]
The easiest way is probably to create a local NuGet feed. 
- Create a folder and copy the package to this folder
- In Visual Studio go to "Tools -> Options" and then find "NuGet Package Manager" on the left, expand it and go to Package Sources. 
- add new feed by providing a name and the path to the folder you created

Once you have created open your project in VS and:
- right click on the References and select Manage NuGet packages
- select the feed you created in the Package source drop down
- you should see the package in package list 
- select the package and on the left and click Install on the right

When you install the package it will update your project file to add a path to include and lib files and also to copy the dll along with your project to the target folder.

**Comment by MyPCIsBetter** [comment]
@moozzyk I'm really sorry that I keep this thread open, but I've come back to it today and can't make it finally done.
NuGet doesn't see my package no matter what path I provide. I originally thought that built package is stored in "[path_to_project]\bin\Win32\Release\dll", but NuGet stubbornly tells that there is no such a thing there. I've even set the path to the folder with entire project, but it also tells that there is no package there.
I hope that I'm doing it in corrently: [[here is how]](http://imgur.com/Zn1V6N5)
So: how this "NuGet feed" should look like to be recognized by Nuget Package Manager?

BTW: isn't it just a c++ code? Why it actually doesn't work in Visual Studio 2015?

**Comment by moozzyk** [comment]
No. Nuget packages are binplaced in the $\artifacts\build folder (search for Microsoft.AspNet.SignalR.Client.Cpp.v140.WinDesktop.1.0.0-alpha1.nupkg - this is your package). What I have on my box is a separate folder (like C:\LocalNuGetFeed) where I copy packages. This way it is very easy for me to tell what packages I have in my local feed. The rest of your settings look good to me. For reference this is how this looks on my box. (I used red boxes to mark things you need to pay attention to (although you seem to be using older tooling?))

![image](https://cloud.githubusercontent.com/assets/1438884/11571992/eaa3b6d6-99b3-11e5-869c-3c273a11f23c.png)

> BTW: isn't it just a c++ code? Why it actually doesn't work in Visual Studio 2015?

It is just a c++ code and this is the reason why it won't/might not work in Visual Studio 2015. The version for VS2013 is linked against CRT that shipped with VS2013. The version for Visual Studio 2015 is linked against CRT that shipped with VS2015. Using different CRTs in one applications may result in unexpected results. Take a look at [this article](http://siomsystems.com/mixing-visual-studio-versions/) to learn more. (From my experience: If you have not worked with CPP Rest SDK/async in C++ before you more than enough crashes to understand/fix that you don't even want to add random crashes from CRT that actually can't be fixed). Starting from VS2015 the approach to CRT has changed - instead of shipping a new version of CRT each time a VS ships there is now a new Universal CRT that can be used regardless of the VS version (>= VS2015) used. ([Here](http://blogs.msdn.com/b/vcblog/archive/2015/03/03/introducing-the-universal-crt.aspx) are the details) So in the future you would be able to use dlls built in VS2015 in apps built in VS vNext. 

Also one thing you may find useful if you are getting started with C++ async is a blog post series of mine on [async programming with C++ Rest SDK](http://blog.3d-logic.com/category/casablanca/)

**Comment by MyPCIsBetter** [comment]
Thanks, works ;)

**Comment by moozzyk** [comment]
Świetnie!
